#! /bin/sh

if test -d fw/bin
  then
    PATH="`pwd`/fw/bin:$PATH"
    export PATH
  fi

fwb=`which fw-bootstrap`

if test -z "$fwb"
  then
    echo "bootstrap: fatal: fw-bootstrap not installed or not in PATH" 1>&2
    exit 1
  fi

"$fwb" --fw_version "0.4.0" --name mondemand-journal-to-rrd --revision svn --template C --svn_project_path https://mondemand.svn.sourceforge.net/svnroot/mondemand/mondemand-journal-to-rrd/trunk --svn_tag_root https://mondemand.svn.sourceforge.net/svnroot/mondemand/mondemand-journal-to-rrd/tags "$@"
