#! /bin/sh

set -e

#---------------------------------------------------------------------
#                            post-install                             
# 
# Executed after the package is installed.
#
# http://code.google.com/p/fwtemplates/wiki/PackageHooks
#---------------------------------------------------------------------

case "$1" in
  configure)
    # most recently configured version is $2 (possibly empty string)
    chmod -R 777 /mnt/mondemand-journaller
    chown -R apache:apache /var/lib/mondemand/
    ;;
  *)
    ;;
esac

exit 0
